name: Build and Test KeepKey Client
on:
  push:
    branches-ignore:
      - main
  pull_request:
    branches:
      - main
      - develop

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['windows-latest']
    steps:
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      - uses: actions/checkout@v1
        with:
          fetch-depth: 0
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14'
          cache: 'npm'
      - run: npm run npm
      - run: npm run build-electron-publish-${{ matrix.os }}
#      - run: npm run test
