name: Lint Commit Messages
on:
  push:
    branches-ignore:
      - main
  pull_request:
    branches:
      - main
      - develop

jobs:
  commitlint:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm run npm
      - run: npm run build-electron-publish-mac
      - run: npm run test
